timeout: 3
default_entry: 1
interface_branding: Josh OS Boot Manager
interface_branding_colour: 48c39f
interface_help_colour: 97a0a8
terse: yes
serial: yes
serial_baudrate: 115200

/Josh OS 0.1
    comment: Native Josh kernel — pre-alpha
    protocol: limine
    path: boot():/boot/kernel
