#ifndef JOSHOS_SYSCALL_ABI_H
#define JOSHOS_SYSCALL_ABI_H

#define JOSH_SYSCALL_ABI_VERSION 1
#define JOSH_SYS_ABI_VERSION 0
#define JOSH_SYS_WRITE 1
#define JOSH_SYS_YIELD 2
#define JOSH_SYS_EXIT 3

#define JOSH_ERR_EFAULT 14
#define JOSH_ERR_ENOSYS 38
#define JOSH_ERR_EINVAL 22

#endif
